services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: prueba-backend-app
        container_name: prueba-backend-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - prueba-network
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: prueba-backend-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - prueba-network

    nginx:
        image: nginx:alpine
        container_name: prueba-backend-nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - prueba-network
        depends_on:
            - app

networks:
    prueba-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
